In [ ]:
import torch
torch.__version__

'2.1.0+cu121'

In [ ]:
scalar = torch.tensor(7)
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([1,2])
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
matrix = torch.tensor([[[1,2,3],[3,4,5]]])
matrix.shape

torch.Size([1, 2, 3])

In [ ]:
random = torch.rand((2,3,3))
random

tensor([[[0.5171, 0.6906, 0.7471],
         [0.2565, 0.4697, 0.4925],
         [0.5636, 0.9516, 0.1039]],

        [[0.7579, 0.0679, 0.4657],
         [0.0989, 0.9710, 0.4972],
         [0.7113, 0.2395, 0.7192]]])

In [ ]:
arr = torch.range(0,10,1, dtype = torch.int)
arr.device

<ipython-input-19-1d578d6c66d0>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  arr = torch.range(0,10,1, dtype = torch.int)


device(type='cpu')

In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
tensor_A = torch.tensor([[1,2], [3,4], [5,6]], dtype = torch.float32)

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(40)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[ 1.2139,  0.6996,  0.7585, -0.9974, -1.0103, -0.6174],
        [ 1.8757,  0.3868,  1.7561, -1.8970, -2.8193, -0.2611],
        [ 2.5375,  0.0740,  2.7536, -2.7966, -4.6283,  0.0952]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [ ]:
tensor = torch.range(10, 100, 10)
tensor

<ipython-input-43-940edae07ade>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  tensor = torch.range(10, 100, 10)


tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
tensor.max()
tensor.mean()

tensor(55.)

In [ ]:
tensor.type(torch.int)

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100], dtype=torch.int32)

In [ ]:
tensor.mean()

tensor(55.)

In [ ]:
torch.squeeze(tensor)

tensor([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [ ]:
test = torch.range(1, 10, 1, dtype = torch.int)
test.shape

<ipython-input-60-d4aca5047326>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  test = torch.range(1, 10, 1, dtype = torch.int)


torch.Size([10])

In [ ]:
test = test.reshape((1,10))
test.shape


torch.Size([1, 10])

In [ ]:
z = test.view((10,1))
z.shape

torch.Size([10, 1])

In [ ]:
test.shape

torch.Size([1, 10])

In [ ]:
z[0][0] = 5

In [ ]:
test

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]], dtype=torch.int32)

In [ ]:
stack = torch.stack([test, test, test], dim = 0)
stack

tensor([[[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

        [[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]],

        [[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]], dtype=torch.int32)

In [ ]:
x= torch.arange(1,10).reshape((1,3,3))
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,1]

tensor([[4, 5, 6]])

In [ ]:
x = torch.rand(7,7)
x

tensor([[0.4917, 0.8641, 0.7517, 0.0550, 0.8804, 0.8346, 0.5550],
        [0.0796, 0.2305, 0.2173, 0.9714, 0.1629, 0.4418, 0.5534],
        [0.6896, 0.5202, 0.8000, 0.2409, 0.6185, 0.6125, 0.9323],
        [0.5449, 0.3402, 0.7433, 0.8701, 0.8250, 0.1613, 0.2592],
        [0.7490, 0.1975, 0.2845, 0.9736, 0.2434, 0.7586, 0.2595],
        [0.4890, 0.8270, 0.0786, 0.1560, 0.6787, 0.0930, 0.9775],
        [0.9102, 0.0620, 0.2329, 0.6532, 0.8248, 0.4113, 0.6617]])

In [ ]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [ ]:
import torch
from torch import nn

In [ ]:
# Create a Linear Regression model class
class LinearRegressionModel(nn.Module): # <- almost everything in PyTorch is a nn.Module (think of this as neural network lego blocks)
    def __init__(self):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(1, # <- start with random weights (this will get adjusted as the model learns)
                                                dtype=torch.float), # <- PyTorch loves float32 by default
                                   requires_grad=True) # <- can we update this value with gradient descent?)

        self.bias = nn.Parameter(torch.randn(1, # <- start with random bias (this will get adjusted as the model learns)
                                            dtype=torch.float), # <- PyTorch loves float32 by default
                                requires_grad=True) # <- can we update this value with gradient descent?))

    # Forward defines the computation in the model
    def forward(self, x: torch.Tensor) -> torch.Tensor: # <- "x" is the input data (e.g. training/testing features)
        return self.weights * x + self.bias # <- this is the linear regression formula (y = m*x + b)

In [ ]:
# Set manual seed since nn.Parameter are randomly initialzied
torch.manual_seed(42)

# Create an instance of the model (this is a subclass of nn.Module that contains nn.Parameter(s))
model_0 = LinearRegressionModel()

# Check the nn.Parameter(s) within the nn.Module subclass we created
list(model_0.parameters())

[Parameter containing:
 tensor([0.3367], requires_grad=True),
 Parameter containing:
 tensor([0.1288], requires_grad=True)]